# Generated by Django 4.1.4 on 2022-12-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('incident_department', models.CharField(max_length=255)),
                ('date_time', models.DateField()),
                ('incidnt_location', models.CharField(max_length=255)),
                ('incident_severity', models.CharField(max_length=255)),
                ('suspected_cause', models.CharField(max_length=255)),
                ('immediate_action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('on_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubIncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=50)),
                ('on_date', models.DateField(auto_now=True)),
                ('indicdent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.incidentmaster')),
            ],
        ),
    ]
